### ISSUE TITLE
jetpack converting to creative jetpack?

### ISSUE THREAD

**Issue by ratedremedy** [Tomson124/SimplyJetpacks-2#11]
Any of the craftable jetpacks turns into a creative jetpack while in use. (Singleplayer using version 2.0.3.14 of the mod)

**Comment by Tomson124** [comment]
I will need more information on this issue...
Which mods (or modpack) do you have installed besides SimplyJetpacks 2? Which version of Forge?
And what do you mean by "turns into creative jetpack"? Does the item change (including texture and energy stats) or does it just have infinite power?

**Comment by ratedremedy** [comment]
BaublesStuff
AppleCore
AppleSkin
Aroma1997's Dimensional World
BaseMetals
BetterBedrockGen
BetterAchievements
BetterBuildersWands
BiomesOPlenty
Botania
ChestTransporter
Chickens
Chisel
Chisels&Bits
CodeChicken Core&Lib
Cooking for Blockheads
CraftTweaker
D3Commands
DarkUtilities
Draconic Evolution
DrawersBits
DynamicLights
EnderCore&IO
EnderStorage
EnderZoo
Expandable backpacks
ExtraUtils2
Extreme Reactors
EZStorage
FastLeafDecay
FTBLib&Utilities
GiacomosFishingNet
Gravestone
Help Fixer
Improving Minecraft
Ingame info XML
Inventory Tweaks
iron chest
JEI
JourneyMaps
JustEnoughResources
Levels
Lots of Food
LunatriusCore
MalisisCore&Doors
Mantle
MikeDongles
modnametooltip
MorePlayerModels
Morpheus
MouseTweaks
MysticalAgriculture
NetherMetals
Netherportalfix
Nomobspawningontrees
optifine
orespawn
pam's harvestcraft
PlayerAPI
projecte
quantumstorage
randomthings
refinedstorage
rftools&dims
simplyjetpacks2
soulshards
storagedrawers
substratum
tconstruct
theoneprobe
tinkers addons
torcherino
translocator
unidict
veinminer

Using latest forge 12.18.2.2116

Any other jetpack I use changes into a physical creative jetpack. (change in texture&energy stats)

**Comment by Tomson124** [comment]
Could you provide a excerpt of the log file from the point where you encountered that issue, and please try Forge version 2099 (the recommended) and see if the issue occurs there, too. I build the mod upon that version and had no issues so likly it is the new Forge version or some other mod in your instance.

**Comment by ratedremedy** [comment]
I've actually encountered the problem originally on Forge 2099. As for the logs, its seems to not update when the change happens.

**Comment by Tomson124** [comment]
The thing is I can't reproduce your probelm in my dev enviroment... Does this problem happen on a server or the client (maybe both? I could try it only client side yet). What exactly do you mean by "not update" Please send me the log r post the excerpt on pastebin.

**Comment by Shadows-of-Fire** [comment]
I had a player report this happening today, not really any information other than his t2 eio jetpack switched to tuberous and then to creative. 
I'll see if I can get any more info.

**Comment by vtgamer** [comment]
I ran into the same issue in a single player world using a custom pack I put together using curse. Anytime I got hit by a mod any of the jetpacks would turn into the creative jetpack. However after removing Levels (https://mods.curse.com/mc-mods/minecraft/235552-levels) this no longer happens.

**Comment by Tomson124** [comment]
@vtgamer and @Shadows-of-Fire Is this occuring on a server or just client side... As I don't have problems with my dev client.

**Comment by vtgamer** [comment]
For me it's the client, not playing on a server. Like I said after removing the levels mod I no longer had any issues. Levels changes armor and weapons so it's my guess that it's doing something odd when it applied experience to the jetpack.

**Comment by Tomson124** [comment]
As @ratedremedy has also installed the Levels mod while he gets the error it is probably related to this mod, please contact the author of the mod, and ask him about the issue, I will see what I can do about the problem on my side.

**Comment by Tomson124** [comment]
Quick update on this one: I tried to contact the author of the Levels mod but he wasn't online since July and his mod wasn't updated since then either... So I guess a fix on his side won't happen, and as I don't want to redo his mod, too, I will look out for a solution on my side but for now you just have to remove the mod if you want to play with mine.

**Comment by a-frenzy** [comment]
https://github.com/TheXFactor117/Levels/issues/121

**Comment by Th3l0stSpart4n** [comment]
I can't currently reproduce this with 1.12.2 versions of both mods.
