### ISSUE TITLE
[Feature request] RF/Tesla Arsenal Support

### ISSUE THREAD

**Issue by Voxel-Friend** [Tomson124/SimplyJetpacks-2#20]
Knoxhacks has made two mods; Redstone Flux Arsenal, and Tesla Arsenal.
https://minecraft.curseforge.com/projects/tesla-arsenal
https://minecraft.curseforge.com/projects/redstone-flux-arsenal
They are essentially spiritual succesors to Restone Arsenal

My request is chestplate/jetpack combos, like was in Simply Jetpacks 1 for 1.7.10, that fits the aesthetic of these mods.

**Comment by Skillotic0703** [comment]
Redstone arsenal was updated so you just need to support RA!

**Comment by Tomson124** [comment]
Is supported in the 1.12.2 version, as the 1.10.2 is discontinued
