### ISSUE TITLE
[Suggestion] Option to enable Ender IO jetpacks and components even if Ender IO isn't detected

### ISSUE THREAD

**Issue by TheDeviantCrafter** [Tomson124/SimplyJetpacks-2#21]
I'm building a modpack that doesn't include Ender IO. As a result, only the creative jetpack and a few other miscellaneous items show up in JEI. I'd like to suggest an option to enable the Ender IO jetpacks and their crafting components even if Ender IO isn't detected. I can add in all the recipes myself via Minetweaker.

**Comment by ToadsworthLP** [comment]
I already added Vanilla-based jetpacks, but it wasn't merged as of now. If you want it now you can compile my fork which contains these. You can find it in the "Pull Requests" tab.

**Comment by Tomson124** [comment]
As @ToadsworthLP already said, a similar feature is already in place in the latest alpha build on curse. But if you have no RF power mod you cannot charge the jetpacks (at least not yet, I am thinking about a solution)
