### ISSUE TITLE
Disabling the Engine/Hover will sometimes effect other players

### ISSUE THREAD

**Issue by Bramblefire123** [Tomson124/SimplyJetpacks-2#25]
A mate and I are playing on SF3 and once in a while one of us would suddenly drop (usually into the void, thank goodness for autohover). After some testing, we discovered that when one of us toggles the engine and/or over, very rarely, the other person's jetpack will also toggle. 

Edit: We are on version 2.0.3.29

**Comment by Tomson124** [comment]
Can you tell me if you were near each other (maybe even tell me how far away you were from each other) and maybe test if it happens when you are far away from each other, too.

**Comment by Bramblefire123** [comment]
Distance between both of us does not seem to matter. We even tried across dimensions (nether specifically) and it had the same effect.

**Comment by Tomson124** [comment]
Cant really tell what it is related to especially as it happens so rarely, but I will keep track of it and see what I can do.

**Comment by thundr** [comment]
Closing from inactivity, if anyone has new information to add please do so.
